In [ ]:
# default_exp klass

# KLASS-funksjoner

> Metoder og funksjoner for å interagere med KLASS

In [ ]:
#hide
# "Hide" blir ikke med i hverken eksportert modul eller dokumentasjonen
from nbdev.showdoc import *

In [ ]:
#export
import requests, json, pandas as pd

In [ ]:
#export
# Med "exports"-kommentaren over så blir koden med i både modulen som eksporteres og dokumentasjonen.
# Med "export"- kommentaren blir ikke kildekoden med i docsene
def get_pandas(URL, level):
    """
    Get pandas dataframe from the KLASS-API

    Parameters
    ----------
    URL : str \n
        url to the API-endpoint you are interested in
    level : str \n
        level of the json to convert, for example 'classificationItems' or 'correspondenceMaps'

    Returns
    -------
    pandas.DataFrame() \n
        The returned json at the level requested, converted to a pandas dataframe

    Further Development
    -------
    Error catching when "level" is not found in the returned json, show the top level json-keys then?

    """
    
    r = requests.get(URL)
    r = r.content.decode('utf8').replace("'", '"')
    r = json.loads(r)
    r = pd.json_normalize(r[level])
    return r

### Vi kan så bruke denne funksjonen for å hente de gjeldende fylkene i ID 1158

In [ ]:
# Uten noen "kommentar"-kode så blir koden kun med i dokumentasjonen, ikke modulen
gjeld_fylke = get_pandas('http://data.ssb.no/api/klass/v1/versions/1158', 'classificationItems')
gjeld_fylke

,code,parentCode,level,name,shortName,notes
0,03,,1,Oslo,None,
1,11,,1,Rogaland,None,
2,15,,1,Møre og Romsdal,None,
3,18,,1,Nordland,None,
4,30,,1,Viken,None,
5,34,,1,Innlandet,None,
6,38,,1,Vestfold og Telemark,None,
7,42,,1,Agder,None,
8,46,,1,Vestland,None,
9,50,,1,Trøndelag - Trööndelage,None,
10,54,,1,Troms og Finnmark – Romsa ja Finnmárku – Troms...,None,
11,99,,1,Uoppgitt,None,